# Generated by Django 4.1.7 on 2023-03-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_foodinstance_eater_alter_foodinstance_fdc_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinstance',
            options={'permissions': (('can_remove_foodinstance', 'remove food'),)},
        ),
    ]
