# Generated by Django 4.1.7 on 2023-03-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_foodinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='biotin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='choline',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='chromium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='copper',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='folate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='histidine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='iodine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='isoleucine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='leucine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='lysine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='magnesium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='manganese',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='methionine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='molybdenum',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='niacin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='pantothenicAcid',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='phenylalanine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='phsophorous',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='riboflavin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='selenium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='thiamin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='threonine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tryptophan',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='valine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminA',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminB12',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminB6',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminC',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminE',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitaminK',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='zinc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
