# Generated by Django 4.1.7 on 2023-03-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_vitaminb9_food_vitaminb6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrient',
            old_name='rdi_male_19y_50y',
            new_name='rdi_male',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='upperTolerance_male_19y_50y',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='rdi_female',
            field=models.PositiveIntegerField(blank=True, help_text='recommended daily intake for adult males 19-50years', null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='upperTolerance',
            field=models.BooleanField(blank=True, help_text='enter an upper tolerance for this nutrient', null=True),
        ),
    ]
