# Generated by Django 4.1.7 on 2023-03-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_rdi_male_19y_50y_nutrient_rdi_male_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodinstance',
            old_name='date',
            new_name='date_eaten',
        ),
    ]
